/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginSmartPanel = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        UserLoginBtn = new javax.swing.JButton();
        AdminLoginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LoginUsernameField = new javax.swing.JTextField();
        LoginPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UserLoginConfirmBtn1 = new javax.swing.JButton();
        CreateUser = new javax.swing.JButton();
        CreateAdmin = new javax.swing.JButton();
        NewAdminForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NewAdminUserNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NewAdminPasswordField = new javax.swing.JPasswordField();
        NewAdminConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        NewAdminConfirmBtn = new javax.swing.JButton();
        BackFromNewAdminBtn = new javax.swing.JButton();
        NewUserForm = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        NewUserUsernameField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NewUserPasswordField = new javax.swing.JPasswordField();
        NewUserConfirmPasswordField = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        NewUserConfirmBtn = new javax.swing.JButton();
        BackFromNewUserBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginSmartPanel.setLayout(new java.awt.CardLayout());

        LoginForm.setBackground(new java.awt.Color(255, 255, 255));
        LoginForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        UserLoginBtn.setText("User");
        UserLoginBtn.addActionListener(this::UserLoginBtnActionPerformed);

        AdminLoginBtn.setText("Admin");
        AdminLoginBtn.addActionListener(this::AdminLoginBtnActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Login As");

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        UserLoginConfirmBtn1.setText("Confirm");
        UserLoginConfirmBtn1.addActionListener(this::UserLoginConfirmBtn1ActionPerformed);

        CreateUser.setText("Create New User");
        CreateUser.addActionListener(this::CreateUserActionPerformed);

        CreateAdmin.setText("Create New Admin");
        CreateAdmin.addActionListener(this::CreateAdminActionPerformed);

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateAdmin)
                    .addComponent(CreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(LoginFormLayout.createSequentialGroup()
                            .addGap(171, 171, 171)
                            .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(73, 73, 73)
                            .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LoginUsernameField)
                                .addComponent(LoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(LoginFormLayout.createSequentialGroup()
                            .addGap(153, 153, 153)
                            .addComponent(jLabel2)
                            .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(LoginFormLayout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(UserLoginConfirmBtn1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                                            .addGap(99, 99, 99)
                                            .addComponent(AdminLoginBtn))
                                        .addGroup(LoginFormLayout.createSequentialGroup()
                                            .addComponent(UserLoginBtn)
                                            .addGap(98, 98, 98))))))))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFormLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UserLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdminLoginBtn)))
                .addGap(33, 33, 33)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LoginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UserLoginConfirmBtn1)
                .addGap(33, 33, 33)
                .addComponent(CreateUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateAdmin)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        LoginSmartPanel.add(LoginForm, "card2");

        NewAdminForm.setBackground(new java.awt.Color(255, 255, 255));
        NewAdminForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        jLabel5.setText("Confirm password:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("New Admin Form");

        NewAdminConfirmBtn.setText("Confirm");

        BackFromNewAdminBtn.setText("Back");
        BackFromNewAdminBtn.addActionListener(this::BackFromNewAdminBtnActionPerformed);

        javax.swing.GroupLayout NewAdminFormLayout = new javax.swing.GroupLayout(NewAdminForm);
        NewAdminForm.setLayout(NewAdminFormLayout);
        NewAdminFormLayout.setHorizontalGroup(
            NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAdminFormLayout.createSequentialGroup()
                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewAdminFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BackFromNewAdminBtn)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel6))
                    .addGroup(NewAdminFormLayout.createSequentialGroup()
                        .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewAdminFormLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addGroup(NewAdminFormLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel5)))
                        .addGap(42, 42, 42)
                        .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewAdminConfirmBtn)
                            .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewAdminPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(NewAdminUserNameField)
                                .addComponent(NewAdminConfirmPasswordField)))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        NewAdminFormLayout.setVerticalGroup(
            NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewAdminFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BackFromNewAdminBtn))
                .addGap(28, 28, 28)
                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NewAdminUserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewAdminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewAdminFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(NewAdminConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(NewAdminConfirmBtn)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        LoginSmartPanel.add(NewAdminForm, "card3");

        NewUserForm.setBackground(new java.awt.Color(255, 255, 255));
        NewUserForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Username:");

        jLabel10.setText("Password:");

        jLabel11.setText("Confirm password:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("New User Form");

        NewUserConfirmBtn.setText("Confirm");

        BackFromNewUserBtn.setText("Back");
        BackFromNewUserBtn.addActionListener(this::BackFromNewUserBtnActionPerformed);

        javax.swing.GroupLayout NewUserFormLayout = new javax.swing.GroupLayout(NewUserForm);
        NewUserForm.setLayout(NewUserFormLayout);
        NewUserFormLayout.setHorizontalGroup(
            NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserFormLayout.createSequentialGroup()
                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewUserFormLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BackFromNewUserBtn)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel12))
                    .addGroup(NewUserFormLayout.createSequentialGroup()
                        .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewUserFormLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(NewUserFormLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel11)))
                        .addGap(42, 42, 42)
                        .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewUserConfirmBtn)
                            .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NewUserPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(NewUserUsernameField)
                                .addComponent(NewUserConfirmPasswordField)))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        NewUserFormLayout.setVerticalGroup(
            NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BackFromNewUserBtn))
                .addGap(28, 28, 28)
                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(NewUserUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewUserFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(NewUserConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(NewUserConfirmBtn)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        LoginSmartPanel.add(NewUserForm, "card4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("PC Component Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LoginSmartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(LoginSmartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserActionPerformed
        // on clicking the create User button the New user creation form will open
        LoginSmartPanel.removeAll();
        LoginSmartPanel.add(NewUserForm);
        LoginSmartPanel.repaint();
        LoginSmartPanel.revalidate();
    }//GEN-LAST:event_CreateUserActionPerformed

    private void CreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAdminActionPerformed
        // on clicking the create Admin btn the new admin creation form will open
        LoginSmartPanel.removeAll();
        LoginSmartPanel.add(NewAdminForm);
        LoginSmartPanel.repaint();
        LoginSmartPanel.revalidate();
    }//GEN-LAST:event_CreateAdminActionPerformed

    private void BackFromNewAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromNewAdminBtnActionPerformed
        // returns back to the Login form from New Admin login form
        LoginSmartPanel.removeAll();
        LoginSmartPanel.add(LoginForm);
        LoginSmartPanel.repaint();
        LoginSmartPanel.revalidate();
    }//GEN-LAST:event_BackFromNewAdminBtnActionPerformed

    private void BackFromNewUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackFromNewUserBtnActionPerformed
        // returns back to the Login form from New User login form
        LoginSmartPanel.removeAll();
        LoginSmartPanel.add(LoginForm);
        LoginSmartPanel.repaint();
        LoginSmartPanel.revalidate();
    }//GEN-LAST:event_BackFromNewUserBtnActionPerformed

    private void UserLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginBtnActionPerformed
        // sets the selectedRole as "USER"
         selectedRole = "USER";
    }//GEN-LAST:event_UserLoginBtnActionPerformed

    private void AdminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginBtnActionPerformed
        // sets the selectedRole as "Admin"
         selectedRole = "ADMIN";
    }//GEN-LAST:event_AdminLoginBtnActionPerformed

    private void UserLoginConfirmBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginConfirmBtn1ActionPerformed
        // TODO add your handling code here:
        LoginController controller = new LoginController(this);
        controller.login();
    }//GEN-LAST:event_UserLoginConfirmBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginBtn;
    private javax.swing.JButton BackFromNewAdminBtn;
    private javax.swing.JButton BackFromNewUserBtn;
    private javax.swing.JButton CreateAdmin;
    private javax.swing.JButton CreateUser;
    private javax.swing.JPanel LoginForm;
    private javax.swing.JPasswordField LoginPasswordField;
    private javax.swing.JPanel LoginSmartPanel;
    private javax.swing.JTextField LoginUsernameField;
    private javax.swing.JButton NewAdminConfirmBtn;
    private javax.swing.JPasswordField NewAdminConfirmPasswordField;
    private javax.swing.JPanel NewAdminForm;
    private javax.swing.JPasswordField NewAdminPasswordField;
    private javax.swing.JTextField NewAdminUserNameField;
    private javax.swing.JButton NewUserConfirmBtn;
    private javax.swing.JPasswordField NewUserConfirmPasswordField;
    private javax.swing.JPanel NewUserForm;
    private javax.swing.JPasswordField NewUserPasswordField;
    private javax.swing.JTextField NewUserUsernameField;
    private javax.swing.JButton UserLoginBtn;
    private javax.swing.JButton UserLoginConfirmBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    //Variable to store the selected login as option
    private String selectedRole = "";

    public String getSelectedRole() {
        return selectedRole;
    }

    public String getUsername() {
        return LoginUsernameField.getText();
    }

    public String getPassword() {
        return new String(LoginPasswordField.getPassword());
}

}
